# config file version: 1.0.1
version: 2
jobs:
  build:
    working_directory: /Users/distiller/launchdarkly/hello-tvos/tmp
    parallelism: 1    # controls the # of containers for the job. In theory, adding another container should halve the number of tests run in each container, but instead appears to run all tests in both containers.
    shell: /bin/bash --login

    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8

    macos:
      xcode: '10.2.1'

    steps:
    - checkout

    - run: 
        name: Make Output Directory
        command: mkdir -p /Users/distiller/launchdarkly/hello-tvos/tmp/output

    - run:
        name: Show xcodebuild Version
        command: xcodebuild -version

    - run:
        name: Clean & Build
        command: set -o pipefail && xcodebuild clean build -project 'hello-tvos.xcodeproj' CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= | tee 'output/xcode_raw.log'

    - run: 
        name: Copy XC Activity Log
        command: find "${HOME}/Library/Developer/Xcode/DerivedData" -name '*.xcactivitylog' -exec cp {} output/xcactivitylog \; || true

    - store_artifacts:
        path: output
        destination: artifacts
