version: 2.1

workflows:
  version: 2
  build_all:
    jobs:
      - build

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: main
    jobs:
    - build

jobs:
  build:
    shell: /bin/bash --login -eo pipefail

    macos:
      xcode: '14.0.1'

    steps:
    - checkout

    - run:
        name: Install carthage
        command: brew install carthage

    - run:
        name: Build carthage projects
        command: carthage update --platform tvOS --use-xcframeworks

    - run:
        name: Make Output Directory
        command: mkdir -p 'artifacts'

    - run:
        name: Build hello-tvos
        command: xcodebuild build -scheme 'hello-tvos' -sdk 'appletvsimulator' CODE_SIGNING_ALLOWED=NO | tee 'artifacts/xcode_build_raw.log' | xcpretty

    - store_artifacts:
        path: artifacts
